import "@/styles/globals.css";
import "swiper/css";
import "swiper/css/scrollbar";
import "swiper/css/autoplay";
import "swiper/css/effect-coverflow";
import "swiper/css/pagination";
import "swiper/css/navigation";

import { Analytics } from "@vercel/analytics/next";
import type { Metadata } from "next";
import { Nanum_Gothic } from "next/font/google";
import localFont from "next/font/local";

import { QueryProvider } from "@/shared/providers";
import AuthProvider from "@/shared/providers/auth-provider";
import NextAuthSessionProvider from "@/shared/providers/session-provider";

export const metadata: Metadata = {
  title: "Artchive",
  description: "Generated by create next app",
};

const nanum_gothic = Nanum_Gothic({
  weight: ["400", "700", "800"],
  variable: "--font-nanum-gothic",
  display: "swap",
  preload: false,
});

const pretendard = localFont({
  src: "../../public/fonts/pretendard/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
  preload: false,
});

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable} ${nanum_gothic.variable}`}
    >
      <body style={{ fontFamily: "var(--font-pretendard)" }}>
        <NextAuthSessionProvider>
          <AuthProvider>
            <QueryProvider>{children}</QueryProvider>
          </AuthProvider>
        </NextAuthSessionProvider>
        <Analytics />
      </body>
    </html>
  );
}
